description = """
    Fix the users group GID.

    Solus never used this group before, however by the time we needed it for
    SAMBA, a systemd update had created a 'users' group with a bogus GID in
    the 900 range, so we forcibly set it back to 100 here before using it
    for anything.
"""

[[update-group-id]]
group-name = "users"
new-group-id = 100
